---
- name: Debian configuration
  when: ansible_os_family == 'Debian'
  block:
    - name: Find runner_gitlab-runner.list file
      ansible.builtin.find:
        paths: /etc/apt/sources.list.d/
        patterns: 'runner_gitlab-runner.list'
      register: find_rc

    - name: Add runner repo
      when: find_rc.matched == 0
      block:
        - name: Download GitLab Runner repository script
          ansible.builtin.get_url:
            url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
            dest: "/tmp/script.deb.sh"
            mode: '0755'

        - name: Execute runner repository script
          ansible.builtin.command: "/tmp/script.deb.sh"
          register: script_rc
          changed_when: script_rc.rc == 0

    - name: Install gitlab-runner
      ansible.builtin.package:
        name: gitlab-runner=15.11.0
        state: present

    - name: Create gitlab-runner user
      ansible.builtin.user:
        name: gitlab-runner

    - name: Register runner with GitLab
      ansible.builtin.command: >
        gitlab-runner register -n -u 'GITLAB_HOST_URL'
        --tls-ca-file /usr/local/share/ca-certificates/ca.crt -r "{{ GL_REGISTRATION_TOKEN }}"
        --executor docker --docker-image alpine:3.18 --tag-list "docker,alpine:3.18"
      register: register_rc
      changed_when: register_rc is changed
