---
- name: Install PostgreSQL and pre-requisites
  ansible.builtin.package:
    name: "{{ pgs_pkgs }}"
    state: present

- name: Create PostgreSQL data directory
  ansible.builtin.file:
    path: /data/pgsql
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Add PostgreSQL NFS share to fstab
  ansible.posix.mount:
    path: /data/pgsql/
    src: nas.$DOMAIN_NAME:/mnt/storage-pool/DBs/services_pgsql
    fstype: nfs
    state: mounted

- name: Stop PostgreSQL systemd service
  ansible.builtin.service:
    name: postgresql
    state: stopped

- name: Point config to PostgreSQL NFS data directory
  ansible.builtin.lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    regexp: '^.*data_directory.*$'
    line: 'data_directory = ''/data/pgsql'''

- name: Make PostgreSQL listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    regexp: '^.*listen_addresses.*$'
    line: 'listen_addresses = ''*'''

- name: Allow any host to access any db from any interface
  ansible.builtin.lineinfile:
    path: /etc/postgresql/15/main/pg_hba.conf
    line: 'host     all    all    0.0.0.0/0    password'
    insertafter: EOF

- name: Start PostgreSQL systemd service
  ansible.builtin.service:
    name: postgresql
    state: started
